doc-warnings: true
test-warnings: false
strictness: high
python-targets:
    - 3
pep8:
    full: true
max-line-length: 80
requirements:
    - matplotlib
    - seaborn
autodetect: true
ignore-paths:
        - data
